### ISSUE TITLE
initial issues with register patient tab

### ISSUE THREAD

**Issue by mrnivlac** [jaymendez/project-lifeline#1]
1. TIME is not updated real time. From observation, need some UI movement  (press key, focus on a new object) for it to be updated.
2. Pressing ENTER while focus is on the Date Of Birth (and other input box like the Contact Number) registers the patient.
3. Nothing happens when CANCEL is pressed.
4. Arrow keys do not work. Cannot always use keyboard to move around the page.
5. Keyboard actions will not work on the Date Of Birth, that is you cannot enter the birth date without a mouse.
6. Required fields to register a patient is Last Name, First Name and Date of Birth. But can register a patient with the same data for the 3 fields. No checking of existing records.
7. A "space" is accepted as input for Last Name and First Name.
8. When Gender dropdown is shown, both Male and Female can be  "highlighted" when using arrow keys to select. "Selected" value is not properly shown to user.

**Comment by jaymendez** [comment]
Fixed on #3
