### ISSUE TITLE
Feature request: display respiration rate from a primary and secondary device

### ISSUE THREAD

**Issue by mrnivlac** [jaymendez/project-lifeline#10]
Primary device uses the observation code: `76171-8`
Secondary device (RxBox) uses the observation code: `76270-8`

Expected behaviour:
1. Read the latest observations for the patient
2. Find the primary RR observation by filtering by code
3. Check if the primary RR observation is not null and not old.
3.a. If so, then display it as the value for RR on the telemetry card.
3.b. If not, then find the secondary RR observation by filtering by code.
3.b.i. Check if the secondary RR observation is not null and not old. If so, then display it as the value for RR on the telemetry card. If not, then show the "no data" message

**Comment by jaymendez** [comment]
Added on #12
