### ISSUE TITLE
default parameter settings should be automatically created for newly registered patients

### ISSUE THREAD

**Issue by mrnivlac** [jaymendez/project-lifeline#17]
![image](https://user-images.githubusercontent.com/4646264/88375152-a34ddc00-cdcd-11ea-9312-9274002a6a7e.png)

The default values should be populated based on these mockup values:
![image](https://user-images.githubusercontent.com/4646264/88375297-ead46800-cdcd-11ea-83f3-cc3e18a4826e.png)

**Comment by jaymendez** [comment]
Fixed
https://github.com/jaymendez/project-lifeline/commit/aa0f7635ef372c98dd3f0eb6466e4013de3f6b66
