### ISSUE TITLE
initial issues with patient list

### ISSUE THREAD

**Issue by mrnivlac** [jaymendez/project-lifeline#2]
1. Rule for sorting for Name column is not clear, do you use the First Name, the Last Name?
2. Nothing happens when Status header is clicked (not sorted).
3. Action header is "sortable" with up/down arrow. Maybe it should NOT be sortable?
4. Only the patient status "ARDS" can be filtered. Filtering with other status show zero results.
5. EDIT and DELETE do not work.
6. Using arrow buttons in the Action highlights both Edit and Delete.

**Comment by jaymendez** [comment]
1. Sortable by first name,
2 -> 6: fixed


Fixed #3
