### ISSUE TITLE
question about colors in telemetry card

### ISSUE THREAD

**Issue by mrnivlac** [jaymendez/project-lifeline#23]
https://github.com/jaymendez/project-lifeline/blob/52aae3831cce2862a8d53f66bce3ee35b2fcad50/src/components/Monitor/Telemetry/Card.jsx#L317

won't this code reset the color of all parameters to `#a9a99d` instead of the individual blue, green, yellow, and white colors in
https://github.com/jaymendez/project-lifeline/blob/52aae3831cce2862a8d53f66bce3ee35b2fcad50/src/components/Monitor/Telemetry/Card.jsx#L46-L60

**Comment by jaymendez** [comment]
fixed
