### ISSUE TITLE
Feature request: Edittable Monitor Number

### ISSUE THREAD

**Issue by mrnivlac** [jaymendez/project-lifeline#24]
In the monitor settings page, the monitor number must be edittable.

Use case: If a user accidentally deletes the monitor, they will need to add a new one and also re-configure the keyboard-less raspberry pi that was previously set to display the old monitor.

Example of current behaviour:
1. Rpi is set to display Monitor 1
2. User deletes Monitor 1
3. User creates a new monitor: Monitor 2
4. User reconfigures the Rpi to load the URL for Monitor 2

Desired behaviour:
1. Rpi is set to display Monitor 1
2. User deletes Monitor 1
3. User creates a new monitor: Monitor 2
4. User edits Monitor 2 to become Monitor 1
5. No changes to Rpi

How the new UI will look:
1. There must be an edit icon beside the monitor name
![edit monitor number](https://user-images.githubusercontent.com/4646264/94420945-6defb100-01b7-11eb-9ccb-288fe35a1111.png)

2. Clicking on the edit icon will open a modal/dialog with a field to edit the monitor number
![image](https://user-images.githubusercontent.com/4646264/94421646-71376c80-01b8-11eb-809a-19bc6f18be0f.png)

**Comment by mrnivlac** [comment]
* Update Rpi to use monitor names instead of monitor ID for the URLS
* Alter constraint to make monitor name unique
* API change
* UI change

**Comment by zheuswalker** [comment]
![image](https://user-images.githubusercontent.com/33520349/94573330-8ee20000-02a4-11eb-813d-7c9b7fe24322.png)
