### ISSUE TITLE
Removal of unused features in the side nav bar

### ISSUE THREAD

**Issue by mrnivlac** [jaymendez/project-lifeline#26]
![image](https://user-images.githubusercontent.com/4646264/94423876-ece6e880-01bb-11eb-92c3-ee1c2865a0f6.png)

Feature | Action
--- | ---
Home | remove
Search bar | remove
Patient registration | no change
Patient list | no change
Monitoring settings | no change
Settings | remove

**Comment by jaymendez** [comment]
fixed on develop
