### ISSUE TITLE
Feature Request: On-demand BP

### ISSUE THREAD

**Issue by mrnivlac** [jaymendez/project-lifeline#28]
Add Actions section to the patient chart.

Example:
![image](https://user-images.githubusercontent.com/4646264/94425423-80b9b400-01be-11eb-838a-bdbcc0fe5519.png)

How it will work:
1. User clicks on "BP NOW"
2. Frontend makes a POST call to the backend
3. Backend will send a Pusher message
4. RxBox will receive the Pusher message
5. RxBox will measure the BP
6. RxBox will create a BP observation

Alternative Solution (HTTP):
1. Rxbox will check DeviceRequest API
2. backend will indicate what patient IDs need to get BP
3. Rxbox will acknowledge the task by making a POST
4. Backend will remove the patient ID from the list of patients to get BP

**Comment by mrnivlac** [comment]
@zheuswalker

**Comment by zheuswalker** [comment]
Things to do to achieve the expected result.

1. **FrontEnd** Call API **requestBP** once user clicked BPNow
http://dev2.rxbox.app:50002/requestBP
params [ patientid ]
![image](https://user-images.githubusercontent.com/33520349/94583218-c4d8b180-02af-11eb-885b-1d3ff55bdf4d.png)
Save the RequestID
![image](https://user-images.githubusercontent.com/33520349/94584021-b2ab4300-02b0-11eb-9579-a321d3ace9e1.png)


2. On the RxBox, when you call the **DeviceRequest** api, check for an array named **onDemandBP_report**
http://dev2.rxbox.app:50002/DeviceRequest?patient=Patient/1
![image](https://user-images.githubusercontent.com/33520349/94584093-c8206d00-02b0-11eb-831c-8c3202eaa5ef.png)
If the RxBox is linked to the patientid on the **onDemandBP_report**  then proceed with step 3

3. Post the BP Value 
http://dev2.rxbox.app:50002/sendrequestBP
params [ requestid&bpvalue ]
![image](https://user-images.githubusercontent.com/33520349/94584274-0322a080-02b1-11eb-9c67-2672c6ea128b.png)

4. On the FrontEnd call the api **getRequestBPValue** with the requestid, call the api every 30 seconds. The expiration of no-bp results is 2 minutes.
http://dev2.rxbox.app:50002/getRequestBPValue
Result
![image](https://user-images.githubusercontent.com/33520349/94584506-4e3cb380-02b1-11eb-98d6-052cd99471f6.png)

**Comment by zheuswalker** [comment]
Things to do to achieve the expected result.

1. **FrontEnd** Call API **requestBP** once user clicked BPNow
http://domain:port/requestBP
params [ patientid ]
![image](https://user-images.githubusercontent.com/33520349/94583218-c4d8b180-02af-11eb-885b-1d3ff55bdf4d.png)
Save the RequestID
![image](https://user-images.githubusercontent.com/33520349/94584021-b2ab4300-02b0-11eb-9579-a321d3ace9e1.png)


2. On the RxBox, when you call the **DeviceRequest** api, check for an array named **onDemandBP_report**
http://domain:port/DeviceRequest?patient=Patient/1
![image](https://user-images.githubusercontent.com/33520349/94584093-c8206d00-02b0-11eb-831c-8c3202eaa5ef.png)
If the RxBox is linked to the patientid on the **onDemandBP_report**  then proceed with step 3

3. Post the BP Value 
http://domain:port/sendrequestBP
params [ requestid&bpvalue ]
![image](https://user-images.githubusercontent.com/33520349/94584274-0322a080-02b1-11eb-9c67-2672c6ea128b.png)

4. On the FrontEnd call the api **getRequestBPValue** with the requestid, call the api every 30 seconds. The expiration of no-bp results is 2 minutes.
http:/domain:port/getRequestBPValue
Result
![image](https://user-images.githubusercontent.com/33520349/94584506-4e3cb380-02b1-11eb-98d6-052cd99471f6.png)

**Comment by mrnivlac** [comment]
For the response in 2, please make it a valid json.
- rupert to send format

For 3, we can forgo the bp value. The BP value will still be sent via the create observation API. It also means we don't need 4 anymore as the value will be read through the usual means.
