### ISSUE TITLE
(1) feature request: when removing a monitor, patient, or patient slot there should be a confirmation dialog

### ISSUE THREAD

**Issue by mrnivlac** [jaymendez/project-lifeline#29]
![Screenshot 2020-10-06 125931](https://user-images.githubusercontent.com/4646264/95160751-e5cf6400-07d3-11eb-9ea4-cfcc26d70e08.png)

Reason: This is to prevent accidental changes.

Confirmation message should be similar as when deleting a patient from the patient list:
![Screenshot 2020-10-06 130340](https://user-images.githubusercontent.com/4646264/95160944-61c9ac00-07d4-11eb-8ca9-c7a2a8524d7a.png)

**Comment by jaymendez** [comment]
fix on latest commit on develop
