### ISSUE TITLE
(1) Bug: BP time frame is not displayed when page is refreshed

### ISSUE THREAD

**Issue by mrnivlac** [jaymendez/project-lifeline#30]
How to replicate:
1. go to the patient chart of a patient
2. edit the parameter settings
3. enter a number in the BP time frame field
4. save
5. refresh the page
6. the BP time frame is now gone

![image](https://user-images.githubusercontent.com/4646264/95161149-f8966880-07d4-11eb-9799-8259778e0436.png)

**Comment by jaymendez** [comment]
fixed on #40
