### ISSUE TITLE
(1) feature request: on demand BP confirmation message

### ISSUE THREAD

**Issue by mrnivlac** [jaymendez/project-lifeline#38]
![image](https://user-images.githubusercontent.com/4646264/95187123-6060a980-07fd-11eb-810c-14c778f8ae66.png)

When the user clicks on BP NOW, a confirmation message should first appear.

Reason: this is to prevent accidental clicks and confirm if the user really wants to get a BP reading

![Screenshot 2020-10-06 130340](https://user-images.githubusercontent.com/4646264/95187366-a61d7200-07fd-11eb-9f0e-e6ba40aa87d8.png)

**Comment by jaymendez** [comment]
fixed on #39
