### ISSUE TITLE
(2) feature request: password login to access the dashboard

### ISSUE THREAD

**Issue by mrnivlac** [jaymendez/project-lifeline#45]
This only covers the patient registration, patient list, patient chart, and monitor settings pages.

Behaviour:
* when user first accesses the URL, the dialog must pop-up
* if the user is idle for more than 30 min, dialog must pop-up
* the password is just a simple 4-digit pin that is settable in the database

![image](https://user-images.githubusercontent.com/4646264/96545799-a75d9d00-12db-11eb-9857-e5bcd7b2b67f.png)

![image](https://user-images.githubusercontent.com/4646264/96546187-5e5a1880-12dc-11eb-8da0-f3b7674c7b7e.png)

**Comment by mrnivlac** [comment]
@zheuswalker

**Comment by zheuswalker** [comment]
Got it.
