### ISSUE TITLE
incorrect observation codes in telemetry card

### ISSUE THREAD

**Issue by mrnivlac** [jaymendez/project-lifeline#5]
Check summary of codes [here](https://docs.google.com/spreadsheets/d/1El_nMojIKa0LehVUqbGQ8jeSoAmEZ5hm2B_e_mDfymg/edit?usp=sharing)

Line 76 of `src/components/Monitor/Telemetry/Card.jsx` on the lifeline2 server was updated to the following:
`const [code] = useState({ ecg: "76282-3", spo2: "59407-7", rr: "76270-8", temp: "8310-5", hr: "8889-8", bp: "131328", });`

**Comment by jaymendez** [comment]
Fixed on #11
