### ISSUE TITLE
Feature request: Error message for old data / no data in telemetry card

### ISSUE THREAD

**Issue by mrnivlac** [jaymendez/project-lifeline#9]
Example where SPO2, RESP, and PR have old/no data:
![image](https://user-images.githubusercontent.com/4646264/83849050-66585800-a741-11ea-9154-0cc23e72b79d.png)

Show the "no data" message when:
* the observation's effectiveDatetime parameter is more than 30s old, OR
* the observation's dataAbsentReason is not empty, OR
* the observation's valueQuantity is empty

**Comment by jaymendez** [comment]
What should happen to the BP data (110/70) when one of the two is missing? 

Also, please define what is the dataAbsentReason here,
![image](https://user-images.githubusercontent.com/28770143/83905769-d512d100-a794-11ea-9099-fb2ad0e04c95.png)

and by valueQuantity (tpo_value), do you mean empty string?

**Comment by mrnivlac** [comment]
If any of the BP values (systolic, diastolic, or MAP) is missing, then don't display the BP. Instead, show the "no data" message.

Sorry for the confusion.

tpo_dataerror = dataAbsentReason

Yes, tpo_value as empty string

**Comment by jaymendez** [comment]
Fixed on #12
